# Generated by Django 4.2.20 on 2025-04-14 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the doctor or facility.", max_length=255
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Doctor"),
                            ("CLINIC", "Clinic"),
                            ("HOSPITAL", "Hospital"),
                        ],
                        default="DOCTOR",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number.",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address (optional).",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Provider's website (optional).",
                        null=True,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True, help_text="State or Province", max_length=100
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "country",
                    models.CharField(blank=True, default="USA", max_length=100),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate (e.g., 40.7128)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate (e.g., -74.0060)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Primary specialty (e.g., Cardiology, General Practice). Comma-separate if multiple for now.",
                        max_length=255,
                    ),
                ),
                (
                    "services_offered",
                    models.TextField(
                        blank=True,
                        help_text="Description of services offered (e.g., Vaccinations, Check-ups, X-Rays). One per line or comma-separated.",
                    ),
                ),
                (
                    "languages_spoken",
                    models.CharField(
                        blank=True,
                        default="English",
                        help_text="Languages spoken by staff (e.g., English, Spanish, French). Comma-separate.",
                        max_length=255,
                    ),
                ),
                (
                    "operating_hours",
                    models.TextField(
                        blank=True,
                        help_text="General operating hours (e.g., Mon-Fri 9am-5pm, Sat 10am-1pm).",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the provider's information has been verified by the platform.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="providers_p_latitud_07070d_idx",
                    ),
                    models.Index(
                        fields=["city", "state_province"],
                        name="providers_p_city_73231d_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="providers_p_is_veri_f6c3b8_idx"
                    ),
                ],
            },
        ),
    ]
