# Generated by Django 4.2.20 on 2025-04-14 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FIRST_AID", "First Aid"),
                            ("SPECIALTY_INFO", "Specialty Information"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The main content (HTML or Markdown potentially)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Content Entries",
                "ordering": ["category", "title"],
            },
        ),
    ]
